services:
  db:
    image: postgres:13.22-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: unless-stopped
    healthcheck:
      # cmd-shell: heavier but req. for env variables
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 20s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dbnet
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
  pgadmin_data:

networks:
  dbnet:
    driver: bridge
